
# Update this file after adding/removing/renaming a target by running
# `cd gluon/ && GLUON_SITEDIR=../ make list-targets | ../contrib/generate-actions.py > ../.github/workflows/build-gluon.yml`
name: Build Gluon
on:
  push:
    branches:
      - build
jobs:

  ar71xx-generic:
    name: ar71xx-generic
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ar71xx-generic

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ar71xx-generic_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ar71xx-generic_output
          path: gluon/output

  ar71xx-tiny:
    name: ar71xx-tiny
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ar71xx-tiny

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ar71xx-tiny_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ar71xx-tiny_output
          path: gluon/output

  ar71xx-nand:
    name: ar71xx-nand
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ar71xx-nand

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ar71xx-nand_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ar71xx-nand_output
          path: gluon/output

  ath79-generic:
    name: ath79-generic
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ath79-generic

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ath79-generic_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ath79-generic_output
          path: gluon/output

  brcm2708-bcm2708:
    name: brcm2708-bcm2708
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh brcm2708-bcm2708

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: brcm2708-bcm2708_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: brcm2708-bcm2708_output
          path: gluon/output

  brcm2708-bcm2709:
    name: brcm2708-bcm2709
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh brcm2708-bcm2709

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: brcm2708-bcm2709_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: brcm2708-bcm2709_output
          path: gluon/output

  ipq40xx-generic:
    name: ipq40xx-generic
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ipq40xx-generic

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ipq40xx-generic_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ipq40xx-generic_output
          path: gluon/output

  ipq806x-generic:
    name: ipq806x-generic
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ipq806x-generic

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ipq806x-generic_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ipq806x-generic_output
          path: gluon/output

  lantiq-xrx200:
    name: lantiq-xrx200
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh lantiq-xrx200

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: lantiq-xrx200_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: lantiq-xrx200_output
          path: gluon/output

  lantiq-xway:
    name: lantiq-xway
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh lantiq-xway

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: lantiq-xway_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: lantiq-xway_output
          path: gluon/output

  mpc85xx-generic:
    name: mpc85xx-generic
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh mpc85xx-generic

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: mpc85xx-generic_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: mpc85xx-generic_output
          path: gluon/output

  mpc85xx-p1020:
    name: mpc85xx-p1020
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh mpc85xx-p1020

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: mpc85xx-p1020_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: mpc85xx-p1020_output
          path: gluon/output

  ramips-mt7620:
    name: ramips-mt7620
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ramips-mt7620

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ramips-mt7620_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ramips-mt7620_output
          path: gluon/output

  ramips-mt7621:
    name: ramips-mt7621
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ramips-mt7621

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ramips-mt7621_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ramips-mt7621_output
          path: gluon/output

  ramips-mt76x8:
    name: ramips-mt76x8
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ramips-mt76x8

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ramips-mt76x8_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ramips-mt76x8_output
          path: gluon/output

  ramips-rt305x:
    name: ramips-rt305x
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh ramips-rt305x

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: ramips-rt305x_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: ramips-rt305x_output
          path: gluon/output

  sunxi-cortexa7:
    name: sunxi-cortexa7
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh sunxi-cortexa7

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: sunxi-cortexa7_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: sunxi-cortexa7_output
          path: gluon/output

  x86-generic:
    name: x86-generic
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh x86-generic

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: x86-generic_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: x86-generic_output
          path: gluon/output

  x86-geode:
    name: x86-geode
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh x86-geode

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: x86-geode_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: x86-geode_output
          path: gluon/output

  x86-legacy:
    name: x86-legacy
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh x86-legacy

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: x86-legacy_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: x86-legacy_output
          path: gluon/output

  x86-64:
    name: x86-64
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt Dependencies
        run: sudo contrib/actions/setup-dependencies.sh

      - name: Build
        run: contrib/actions/run-build.sh x86-64

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: x86-64_logs
          path: gluon/openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: x86-64_output
          path: gluon/output

